services:
  db:
    image: mysql:8.0
    container_name: wallet_core_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet_core_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql

  server:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  mysql_db: