services:
  db:
    image: mysql:8.0
    container_name: wallet_core_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet_core_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql

volumes:
  mysql_db: