services:
  wallet_core_db:
    image: mysql:8.0
    container_name: wallet_core_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet_core_db
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - matepay-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - wallet_core_db
    networks:
      - matepay-network

networks:
  matepay-network:
    external: true

volumes:
  mysql_db: