services:
  balances_db:
    image: mysql:8.0
    container_name: balances_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: balances_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - matepay-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:   
      - matepay-network

volumes:
  mysql_db:

networks:
  matepay-network:
    external: true